//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020-2022 VMware Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	fmtx "fmt"
	osx "os"
	reflectx "reflect"

	v1 "dies.dev/apis/meta/v1"
	apis "github.com/vmware-labs/reconciler-runtime/apis"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	jsonpath "k8s.io/client-go/util/jsonpath"
	yaml "sigs.k8s.io/yaml"

	conventionsv1alpha1 "github.com/vmware-tanzu/cartographer-conventions/pkg/apis/conventions/v1alpha1"
)

var ClusterPodConventionBlank = (&ClusterPodConventionDie{}).DieFeed(conventionsv1alpha1.ClusterPodConvention{})

type ClusterPodConventionDie struct {
	v1.FrozenObjectMeta
	mutable bool
	r       conventionsv1alpha1.ClusterPodConvention
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ClusterPodConventionDie) DieImmutable(immutable bool) *ClusterPodConventionDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ClusterPodConventionDie) DieFeed(r conventionsv1alpha1.ClusterPodConvention) *ClusterPodConventionDie {
	if d.mutable {
		d.FrozenObjectMeta = v1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &ClusterPodConventionDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ClusterPodConventionDie) DieFeedPtr(r *conventionsv1alpha1.ClusterPodConvention) *ClusterPodConventionDie {
	if r == nil {
		r = &conventionsv1alpha1.ClusterPodConvention{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ClusterPodConventionDie) DieFeedJSON(j []byte) *ClusterPodConventionDie {
	r := conventionsv1alpha1.ClusterPodConvention{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ClusterPodConventionDie) DieFeedYAML(y []byte) *ClusterPodConventionDie {
	r := conventionsv1alpha1.ClusterPodConvention{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ClusterPodConventionDie) DieFeedYAMLFile(name string) *ClusterPodConventionDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ClusterPodConventionDie) DieFeedRawExtension(raw runtime.RawExtension) *ClusterPodConventionDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ClusterPodConventionDie) DieRelease() conventionsv1alpha1.ClusterPodConvention {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ClusterPodConventionDie) DieReleasePtr() *conventionsv1alpha1.ClusterPodConvention {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object. Panics on error.
func (d *ClusterPodConventionDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	if err != nil {
		panic(err)
	}
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ClusterPodConventionDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ClusterPodConventionDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ClusterPodConventionDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ClusterPodConventionDie) DieStamp(fn func(r *conventionsv1alpha1.ClusterPodConvention)) *ClusterPodConventionDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ClusterPodConventionDie) DieStampAt(jp string, fn interface{}) *ClusterPodConventionDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConvention) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ClusterPodConventionDie) DeepCopy() *ClusterPodConventionDie {
	r := *d.r.DeepCopy()
	return &ClusterPodConventionDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

var _ runtime.Object = (*ClusterPodConventionDie)(nil)

func (d *ClusterPodConventionDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *ClusterPodConventionDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *ClusterPodConventionDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *ClusterPodConventionDie) UnmarshalJSON(b []byte) error {
	if d == ClusterPodConventionBlank {
		return fmtx.Errorf("cannot unmarshal into the blank die, create a copy first")
	}
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	r := &conventionsv1alpha1.ClusterPodConvention{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *ClusterPodConventionDie) APIVersion(v string) *ClusterPodConventionDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConvention) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *ClusterPodConventionDie) Kind(v string) *ClusterPodConventionDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConvention) {
		r.Kind = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *ClusterPodConventionDie) MetadataDie(fn func(d *v1.ObjectMetaDie)) *ClusterPodConventionDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConvention) {
		d := v1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// SpecDie stamps the resource's spec field with a mutable die.
func (d *ClusterPodConventionDie) SpecDie(fn func(d *ClusterPodConventionSpecDie)) *ClusterPodConventionDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConvention) {
		d := ClusterPodConventionSpecBlank.DieImmutable(false).DieFeed(r.Spec)
		fn(d)
		r.Spec = d.DieRelease()
	})
}

func (d *ClusterPodConventionDie) Spec(v conventionsv1alpha1.ClusterPodConventionSpec) *ClusterPodConventionDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConvention) {
		r.Spec = v
	})
}

var ClusterPodConventionSpecBlank = (&ClusterPodConventionSpecDie{}).DieFeed(conventionsv1alpha1.ClusterPodConventionSpec{})

type ClusterPodConventionSpecDie struct {
	mutable bool
	r       conventionsv1alpha1.ClusterPodConventionSpec
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ClusterPodConventionSpecDie) DieImmutable(immutable bool) *ClusterPodConventionSpecDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ClusterPodConventionSpecDie) DieFeed(r conventionsv1alpha1.ClusterPodConventionSpec) *ClusterPodConventionSpecDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ClusterPodConventionSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ClusterPodConventionSpecDie) DieFeedPtr(r *conventionsv1alpha1.ClusterPodConventionSpec) *ClusterPodConventionSpecDie {
	if r == nil {
		r = &conventionsv1alpha1.ClusterPodConventionSpec{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ClusterPodConventionSpecDie) DieFeedJSON(j []byte) *ClusterPodConventionSpecDie {
	r := conventionsv1alpha1.ClusterPodConventionSpec{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ClusterPodConventionSpecDie) DieFeedYAML(y []byte) *ClusterPodConventionSpecDie {
	r := conventionsv1alpha1.ClusterPodConventionSpec{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ClusterPodConventionSpecDie) DieFeedYAMLFile(name string) *ClusterPodConventionSpecDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ClusterPodConventionSpecDie) DieFeedRawExtension(raw runtime.RawExtension) *ClusterPodConventionSpecDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ClusterPodConventionSpecDie) DieRelease() conventionsv1alpha1.ClusterPodConventionSpec {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ClusterPodConventionSpecDie) DieReleasePtr() *conventionsv1alpha1.ClusterPodConventionSpec {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ClusterPodConventionSpecDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ClusterPodConventionSpecDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ClusterPodConventionSpecDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ClusterPodConventionSpecDie) DieStamp(fn func(r *conventionsv1alpha1.ClusterPodConventionSpec)) *ClusterPodConventionSpecDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ClusterPodConventionSpecDie) DieStampAt(jp string, fn interface{}) *ClusterPodConventionSpecDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionSpec) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ClusterPodConventionSpecDie) DeepCopy() *ClusterPodConventionSpecDie {
	r := *d.r.DeepCopy()
	return &ClusterPodConventionSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// Label selector for workloads. It must match the workload's pod template's labels.
func (d *ClusterPodConventionSpecDie) Selectors(v ...metav1.LabelSelector) *ClusterPodConventionSpecDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionSpec) {
		r.Selectors = v
	})
}

func (d *ClusterPodConventionSpecDie) SelectorTarget(v conventionsv1alpha1.SelectorTargetSource) *ClusterPodConventionSpecDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionSpec) {
		r.SelectorTarget = v
	})
}

func (d *ClusterPodConventionSpecDie) Priority(v conventionsv1alpha1.PriorityLevel) *ClusterPodConventionSpecDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionSpec) {
		r.Priority = v
	})
}

func (d *ClusterPodConventionSpecDie) Webhook(v *conventionsv1alpha1.ClusterPodConventionWebhook) *ClusterPodConventionSpecDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionSpec) {
		r.Webhook = v
	})
}

var ClusterPodConventionWebhookBlank = (&ClusterPodConventionWebhookDie{}).DieFeed(conventionsv1alpha1.ClusterPodConventionWebhook{})

type ClusterPodConventionWebhookDie struct {
	mutable bool
	r       conventionsv1alpha1.ClusterPodConventionWebhook
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ClusterPodConventionWebhookDie) DieImmutable(immutable bool) *ClusterPodConventionWebhookDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ClusterPodConventionWebhookDie) DieFeed(r conventionsv1alpha1.ClusterPodConventionWebhook) *ClusterPodConventionWebhookDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ClusterPodConventionWebhookDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ClusterPodConventionWebhookDie) DieFeedPtr(r *conventionsv1alpha1.ClusterPodConventionWebhook) *ClusterPodConventionWebhookDie {
	if r == nil {
		r = &conventionsv1alpha1.ClusterPodConventionWebhook{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ClusterPodConventionWebhookDie) DieFeedJSON(j []byte) *ClusterPodConventionWebhookDie {
	r := conventionsv1alpha1.ClusterPodConventionWebhook{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ClusterPodConventionWebhookDie) DieFeedYAML(y []byte) *ClusterPodConventionWebhookDie {
	r := conventionsv1alpha1.ClusterPodConventionWebhook{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ClusterPodConventionWebhookDie) DieFeedYAMLFile(name string) *ClusterPodConventionWebhookDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ClusterPodConventionWebhookDie) DieFeedRawExtension(raw runtime.RawExtension) *ClusterPodConventionWebhookDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ClusterPodConventionWebhookDie) DieRelease() conventionsv1alpha1.ClusterPodConventionWebhook {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ClusterPodConventionWebhookDie) DieReleasePtr() *conventionsv1alpha1.ClusterPodConventionWebhook {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ClusterPodConventionWebhookDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ClusterPodConventionWebhookDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ClusterPodConventionWebhookDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ClusterPodConventionWebhookDie) DieStamp(fn func(r *conventionsv1alpha1.ClusterPodConventionWebhook)) *ClusterPodConventionWebhookDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ClusterPodConventionWebhookDie) DieStampAt(jp string, fn interface{}) *ClusterPodConventionWebhookDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionWebhook) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ClusterPodConventionWebhookDie) DeepCopy() *ClusterPodConventionWebhookDie {
	r := *d.r.DeepCopy()
	return &ClusterPodConventionWebhookDie{
		mutable: d.mutable,
		r:       r,
	}
}

// ClientConfig defines how to communicate with the convention.
func (d *ClusterPodConventionWebhookDie) ClientConfig(v admissionregistrationv1.WebhookClientConfig) *ClusterPodConventionWebhookDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionWebhook) {
		r.ClientConfig = v
	})
}

// Certificate references a cert-manager Certificate resource whose CA should be trusted.
func (d *ClusterPodConventionWebhookDie) Certificate(v *conventionsv1alpha1.ClusterPodConventionWebhookCertificate) *ClusterPodConventionWebhookDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionWebhook) {
		r.Certificate = v
	})
}

var ClusterPodConventionWebhookCertificateBlank = (&ClusterPodConventionWebhookCertificateDie{}).DieFeed(conventionsv1alpha1.ClusterPodConventionWebhookCertificate{})

type ClusterPodConventionWebhookCertificateDie struct {
	mutable bool
	r       conventionsv1alpha1.ClusterPodConventionWebhookCertificate
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ClusterPodConventionWebhookCertificateDie) DieImmutable(immutable bool) *ClusterPodConventionWebhookCertificateDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ClusterPodConventionWebhookCertificateDie) DieFeed(r conventionsv1alpha1.ClusterPodConventionWebhookCertificate) *ClusterPodConventionWebhookCertificateDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ClusterPodConventionWebhookCertificateDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ClusterPodConventionWebhookCertificateDie) DieFeedPtr(r *conventionsv1alpha1.ClusterPodConventionWebhookCertificate) *ClusterPodConventionWebhookCertificateDie {
	if r == nil {
		r = &conventionsv1alpha1.ClusterPodConventionWebhookCertificate{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ClusterPodConventionWebhookCertificateDie) DieFeedJSON(j []byte) *ClusterPodConventionWebhookCertificateDie {
	r := conventionsv1alpha1.ClusterPodConventionWebhookCertificate{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ClusterPodConventionWebhookCertificateDie) DieFeedYAML(y []byte) *ClusterPodConventionWebhookCertificateDie {
	r := conventionsv1alpha1.ClusterPodConventionWebhookCertificate{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ClusterPodConventionWebhookCertificateDie) DieFeedYAMLFile(name string) *ClusterPodConventionWebhookCertificateDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ClusterPodConventionWebhookCertificateDie) DieFeedRawExtension(raw runtime.RawExtension) *ClusterPodConventionWebhookCertificateDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ClusterPodConventionWebhookCertificateDie) DieRelease() conventionsv1alpha1.ClusterPodConventionWebhookCertificate {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ClusterPodConventionWebhookCertificateDie) DieReleasePtr() *conventionsv1alpha1.ClusterPodConventionWebhookCertificate {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ClusterPodConventionWebhookCertificateDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ClusterPodConventionWebhookCertificateDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ClusterPodConventionWebhookCertificateDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ClusterPodConventionWebhookCertificateDie) DieStamp(fn func(r *conventionsv1alpha1.ClusterPodConventionWebhookCertificate)) *ClusterPodConventionWebhookCertificateDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ClusterPodConventionWebhookCertificateDie) DieStampAt(jp string, fn interface{}) *ClusterPodConventionWebhookCertificateDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionWebhookCertificate) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ClusterPodConventionWebhookCertificateDie) DeepCopy() *ClusterPodConventionWebhookCertificateDie {
	r := *d.r.DeepCopy()
	return &ClusterPodConventionWebhookCertificateDie{
		mutable: d.mutable,
		r:       r,
	}
}

func (d *ClusterPodConventionWebhookCertificateDie) Namespace(v string) *ClusterPodConventionWebhookCertificateDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionWebhookCertificate) {
		r.Namespace = v
	})
}

func (d *ClusterPodConventionWebhookCertificateDie) Name(v string) *ClusterPodConventionWebhookCertificateDie {
	return d.DieStamp(func(r *conventionsv1alpha1.ClusterPodConventionWebhookCertificate) {
		r.Name = v
	})
}

var PodIntentBlank = (&PodIntentDie{}).DieFeed(conventionsv1alpha1.PodIntent{})

type PodIntentDie struct {
	v1.FrozenObjectMeta
	mutable bool
	r       conventionsv1alpha1.PodIntent
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *PodIntentDie) DieImmutable(immutable bool) *PodIntentDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *PodIntentDie) DieFeed(r conventionsv1alpha1.PodIntent) *PodIntentDie {
	if d.mutable {
		d.FrozenObjectMeta = v1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &PodIntentDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *PodIntentDie) DieFeedPtr(r *conventionsv1alpha1.PodIntent) *PodIntentDie {
	if r == nil {
		r = &conventionsv1alpha1.PodIntent{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *PodIntentDie) DieFeedJSON(j []byte) *PodIntentDie {
	r := conventionsv1alpha1.PodIntent{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *PodIntentDie) DieFeedYAML(y []byte) *PodIntentDie {
	r := conventionsv1alpha1.PodIntent{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *PodIntentDie) DieFeedYAMLFile(name string) *PodIntentDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodIntentDie) DieFeedRawExtension(raw runtime.RawExtension) *PodIntentDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *PodIntentDie) DieRelease() conventionsv1alpha1.PodIntent {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *PodIntentDie) DieReleasePtr() *conventionsv1alpha1.PodIntent {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object. Panics on error.
func (d *PodIntentDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	if err != nil {
		panic(err)
	}
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *PodIntentDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *PodIntentDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodIntentDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *PodIntentDie) DieStamp(fn func(r *conventionsv1alpha1.PodIntent)) *PodIntentDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *PodIntentDie) DieStampAt(jp string, fn interface{}) *PodIntentDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntent) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *PodIntentDie) DeepCopy() *PodIntentDie {
	r := *d.r.DeepCopy()
	return &PodIntentDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

var _ runtime.Object = (*PodIntentDie)(nil)

func (d *PodIntentDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *PodIntentDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *PodIntentDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *PodIntentDie) UnmarshalJSON(b []byte) error {
	if d == PodIntentBlank {
		return fmtx.Errorf("cannot unmarshal into the blank die, create a copy first")
	}
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	r := &conventionsv1alpha1.PodIntent{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *PodIntentDie) APIVersion(v string) *PodIntentDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntent) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *PodIntentDie) Kind(v string) *PodIntentDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntent) {
		r.Kind = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *PodIntentDie) MetadataDie(fn func(d *v1.ObjectMetaDie)) *PodIntentDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntent) {
		d := v1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// SpecDie stamps the resource's spec field with a mutable die.
func (d *PodIntentDie) SpecDie(fn func(d *PodIntentSpecDie)) *PodIntentDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntent) {
		d := PodIntentSpecBlank.DieImmutable(false).DieFeed(r.Spec)
		fn(d)
		r.Spec = d.DieRelease()
	})
}

// StatusDie stamps the resource's status field with a mutable die.
func (d *PodIntentDie) StatusDie(fn func(d *PodIntentStatusDie)) *PodIntentDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntent) {
		d := PodIntentStatusBlank.DieImmutable(false).DieFeed(r.Status)
		fn(d)
		r.Status = d.DieRelease()
	})
}

func (d *PodIntentDie) Spec(v conventionsv1alpha1.PodIntentSpec) *PodIntentDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntent) {
		r.Spec = v
	})
}

func (d *PodIntentDie) Status(v conventionsv1alpha1.PodIntentStatus) *PodIntentDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntent) {
		r.Status = v
	})
}

var PodIntentSpecBlank = (&PodIntentSpecDie{}).DieFeed(conventionsv1alpha1.PodIntentSpec{})

type PodIntentSpecDie struct {
	mutable bool
	r       conventionsv1alpha1.PodIntentSpec
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *PodIntentSpecDie) DieImmutable(immutable bool) *PodIntentSpecDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *PodIntentSpecDie) DieFeed(r conventionsv1alpha1.PodIntentSpec) *PodIntentSpecDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &PodIntentSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *PodIntentSpecDie) DieFeedPtr(r *conventionsv1alpha1.PodIntentSpec) *PodIntentSpecDie {
	if r == nil {
		r = &conventionsv1alpha1.PodIntentSpec{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *PodIntentSpecDie) DieFeedJSON(j []byte) *PodIntentSpecDie {
	r := conventionsv1alpha1.PodIntentSpec{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *PodIntentSpecDie) DieFeedYAML(y []byte) *PodIntentSpecDie {
	r := conventionsv1alpha1.PodIntentSpec{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *PodIntentSpecDie) DieFeedYAMLFile(name string) *PodIntentSpecDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodIntentSpecDie) DieFeedRawExtension(raw runtime.RawExtension) *PodIntentSpecDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *PodIntentSpecDie) DieRelease() conventionsv1alpha1.PodIntentSpec {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *PodIntentSpecDie) DieReleasePtr() *conventionsv1alpha1.PodIntentSpec {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *PodIntentSpecDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *PodIntentSpecDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodIntentSpecDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *PodIntentSpecDie) DieStamp(fn func(r *conventionsv1alpha1.PodIntentSpec)) *PodIntentSpecDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *PodIntentSpecDie) DieStampAt(jp string, fn interface{}) *PodIntentSpecDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntentSpec) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *PodIntentSpecDie) DeepCopy() *PodIntentSpecDie {
	r := *d.r.DeepCopy()
	return &PodIntentSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// ServiceAccountName is the name of the Kubernetes ServiceAccount used to authenticate the image pull if the service account has attached pull secrets. For more information: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account
func (d *PodIntentSpecDie) ServiceAccountName(v string) *PodIntentSpecDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntentSpec) {
		r.ServiceAccountName = v
	})
}

// ImagePullSecrets contains the names of the Kubernetes Secrets containing registry login information to resolve image metadata.
func (d *PodIntentSpecDie) ImagePullSecrets(v ...corev1.LocalObjectReference) *PodIntentSpecDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntentSpec) {
		r.ImagePullSecrets = v
	})
}

// Template defines the workload pod temple
func (d *PodIntentSpecDie) Template(v conventionsv1alpha1.PodTemplateSpec) *PodIntentSpecDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntentSpec) {
		r.Template = v
	})
}

var PodIntentStatusBlank = (&PodIntentStatusDie{}).DieFeed(conventionsv1alpha1.PodIntentStatus{})

type PodIntentStatusDie struct {
	mutable bool
	r       conventionsv1alpha1.PodIntentStatus
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *PodIntentStatusDie) DieImmutable(immutable bool) *PodIntentStatusDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *PodIntentStatusDie) DieFeed(r conventionsv1alpha1.PodIntentStatus) *PodIntentStatusDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &PodIntentStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *PodIntentStatusDie) DieFeedPtr(r *conventionsv1alpha1.PodIntentStatus) *PodIntentStatusDie {
	if r == nil {
		r = &conventionsv1alpha1.PodIntentStatus{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *PodIntentStatusDie) DieFeedJSON(j []byte) *PodIntentStatusDie {
	r := conventionsv1alpha1.PodIntentStatus{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *PodIntentStatusDie) DieFeedYAML(y []byte) *PodIntentStatusDie {
	r := conventionsv1alpha1.PodIntentStatus{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *PodIntentStatusDie) DieFeedYAMLFile(name string) *PodIntentStatusDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodIntentStatusDie) DieFeedRawExtension(raw runtime.RawExtension) *PodIntentStatusDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *PodIntentStatusDie) DieRelease() conventionsv1alpha1.PodIntentStatus {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *PodIntentStatusDie) DieReleasePtr() *conventionsv1alpha1.PodIntentStatus {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *PodIntentStatusDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *PodIntentStatusDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodIntentStatusDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *PodIntentStatusDie) DieStamp(fn func(r *conventionsv1alpha1.PodIntentStatus)) *PodIntentStatusDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *PodIntentStatusDie) DieStampAt(jp string, fn interface{}) *PodIntentStatusDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntentStatus) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *PodIntentStatusDie) DeepCopy() *PodIntentStatusDie {
	r := *d.r.DeepCopy()
	return &PodIntentStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

func (d *PodIntentStatusDie) Status(v apis.Status) *PodIntentStatusDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntentStatus) {
		r.Status = v
	})
}

func (d *PodIntentStatusDie) Template(v *conventionsv1alpha1.PodTemplateSpec) *PodIntentStatusDie {
	return d.DieStamp(func(r *conventionsv1alpha1.PodIntentStatus) {
		r.Template = v
	})
}
