//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020-2022 VMware Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BOM) DeepCopyInto(out *BOM) {
	*out = *in
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BOM.
func (in *BOM) DeepCopy() *BOM {
	if in == nil {
		return nil
	}
	out := new(BOM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
	if in.BOMs != nil {
		in, out := &in.BOMs, &out.BOMs
		*out = make([]BOM, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConventionContext) DeepCopyInto(out *PodConventionContext) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConventionContextSpec) DeepCopyInto(out *PodConventionContextSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.ImageConfig != nil {
		in, out := &in.ImageConfig, &out.ImageConfig
		*out = make([]ImageConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConventionContextSpec.
func (in *PodConventionContextSpec) DeepCopy() *PodConventionContextSpec {
	if in == nil {
		return nil
	}
	out := new(PodConventionContextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConventionContextStatus) DeepCopyInto(out *PodConventionContextStatus) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.AppliedConventions != nil {
		in, out := &in.AppliedConventions, &out.AppliedConventions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConventionContextStatus.
func (in *PodConventionContextStatus) DeepCopy() *PodConventionContextStatus {
	if in == nil {
		return nil
	}
	out := new(PodConventionContextStatus)
	in.DeepCopyInto(out)
	return out
}
