# Output collected with the dumper-server sample using the workload from the 
# spring-convention-server sample. The raw bytes sent via the webhook will be 
# JSON, rendering a YAML for human readability.

---
apiVersion: webhooks.conventions.carto.run/v1alpha1
kind: PodConventionContext
metadata:
  creationTimestamp: null
  name: spring-sample-dumper
spec:
  imageConfig:
  - boms:
    - name: cnb-app:/layers/sbom/launch/paketo-buildpacks_bellsoft-liberica/helper/sbom.syft.json
      raw:   < ----- BASE64 ENCODED DATA  ---->
    - name: cnb-app:/layers/sbom/launch/paketo-buildpacks_bellsoft-liberica/jre/sbom.syft.json
      raw: |
        # redacted
        < ----- BASE64 ENCODED DATA  ---->
    - name: cnb-app:/layers/sbom/launch/paketo-buildpacks_ca-certificates/helper/sbom.syft.json
      raw: |
        # redacted
        < ----- BASE64 ENCODED DATA  ---->
    - name: cnb-app:/layers/sbom/launch/paketo-buildpacks_executable-jar/sbom.cdx.json
      raw: |
        # redacted
        < ----- BASE64 ENCODED DATA  ---->
    - name: cnb-app:/layers/sbom/launch/paketo-buildpacks_executable-jar/sbom.syft.json
      raw: |
        # redacted
        < ----- BASE64 ENCODED DATA  ---->
    - name: cnb-app:/layers/sbom/launch/paketo-buildpacks_spring-boot/helper/sbom.syft.json
      raw: |
       # redacted
       < ----- BASE64 ENCODED DATA  ---->
    - name: cnb-app:/layers/sbom/launch/paketo-buildpacks_spring-boot/spring-cloud-bindings/sbom.syft.json
      raw: |
        # redacted
        < ----- BASE64 ENCODED DATA  ---->
    config:
      architecture: amd64
      config:
        Entrypoint:
        - /cnb/process/web
        Env:
        - PATH=/cnb/process:/cnb/lifecycle:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - CNB_LAYERS_DIR=/layers
        - CNB_APP_DIR=/workspace
        - CNB_PLATFORM_API=0.8
        - CNB_DEPRECATION_MODE=quiet
        Image: sha256:f1850551d4511c96f02e4bd705e502928022035d55e763c374348d7b599ac8cd
        Labels:
          io.buildpacks.build.metadata: '{"bom":null,"buildpacks":[{"homepage":"https://github.com/paketo-buildpacks/ca-certificates","id":"paketo-buildpacks/ca-certificates","version":"3.0.1"},{"homepage":"https://github.com/paketo-buildpacks/bellsoft-liberica","id":"paketo-buildpacks/bellsoft-liberica","version":"9.0.1"},{"homepage":"https://github.com/paketo-buildpacks/syft","id":"paketo-buildpacks/syft","version":"1.2.0"},{"homepage":"https://github.com/paketo-buildpacks/maven","id":"paketo-buildpacks/maven","version":"6.0.1"},{"homepage":"https://github.com/paketo-buildpacks/executable-jar","id":"paketo-buildpacks/executable-jar","version":"6.0.1"},{"homepage":"https://github.com/paketo-buildpacks/apache-tomcat","id":"paketo-buildpacks/apache-tomcat","version":"7.0.2"},{"homepage":"https://github.com/paketo-buildpacks/dist-zip","id":"paketo-buildpacks/dist-zip","version":"5.0.1"},{"homepage":"https://github.com/paketo-buildpacks/spring-boot","id":"paketo-buildpacks/spring-boot","version":"5.2.0"}],"launcher":{"version":"0.13.1","source":{"git":{"repository":"github.com/buildpacks/lifecycle","commit":"071939da"}}},"processes":[{"type":"executable-jar","command":"java","args":["org.springframework.boot.loader.JarLauncher"],"direct":true,"buildpackID":"paketo-buildpacks/executable-jar"},{"type":"task","command":"java","args":["org.springframework.boot.loader.JarLauncher"],"direct":true,"buildpackID":"paketo-buildpacks/executable-jar"},{"type":"web","command":"java","args":["org.springframework.boot.loader.JarLauncher"],"direct":true,"buildpackID":"paketo-buildpacks/executable-jar"}],"buildpack-default-process-type":"web"}'
          io.buildpacks.lifecycle.metadata: '{"app":[{"sha":"sha256:a9e7448454f5fe4f6be1bc4a31004534d4dfeb1e743e11946d335b26ae8c17b2"},{"sha":"sha256:c4537747ad1efb1f098a319cad22cb13212d9b2c325c48ef9154078d4eeb8868"},{"sha":"sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"},{"sha":"sha256:0f31e5b545554dfba40f6b369be06ac78c21190059d9166abbf46807aeac3cc0"},{"sha":"sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"}],"sbom":{"sha":"sha256:4918492351c161334d213aa73bcfbe92fcb4f06ebfdc9e2de11916d111f10f52"},"buildpacks":[{"key":"paketo-buildpacks/ca-certificates","version":"3.0.1","layers":{"helper":{"sha":"sha256:56d5429304369d4c23b02aab20fd2667ef20ca47c579e02a361c249dedbfd5c2","data":{"clear-env":false,"description":"A
            Cloud Native Buildpack that adds custom CA certificates to a build and
            a created image","homepage":"https://github.com/paketo-buildpacks/ca-certificates","id":"paketo-buildpacks/ca-certificates","keywords":["ca-certificates","trust","certificates"],"licenses":[{"type":"Apache-2.0","uri":"https://github.com/paketo-buildpacks/ca-certificates/blob/main/LICENSE"}],"name":"Paketo
            CA Certificates Buildpack","sbom-formats":["application/vnd.cyclonedx+json","application/vnd.syft+json"],"version":"3.0.1"},"build":false,"launch":true,"cache":false}}},{"key":"paketo-buildpacks/bellsoft-liberica","version":"9.0.1","layers":{"helper":{"sha":"sha256:1c3471643466fbf59df09102442337e03876bb1c8ee9b28140da48510ed87d4a","data":{"clear-env":false,"description":"A
            Cloud Native Buildpack that provides the Bellsoft Liberica implementations
            of JREs and JDKs","homepage":"https://github.com/paketo-buildpacks/bellsoft-liberica","id":"paketo-buildpacks/bellsoft-liberica","keywords":["java","jvm","jre","jdk"],"licenses":[{"type":"Apache-2.0","uri":"https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/LICENSE"}],"name":"Paketo
            BellSoft Liberica Buildpack","sbom-formats":["application/vnd.syft+json","application/vnd.cyclonedx+json"],"version":"9.0.1"},"build":false,"launch":true,"cache":false},"java-security-properties":{"sha":"sha256:ec0381c8f32136ad9564b114b2271d1181e0c181957acb6707e6ff4713a7a89d","data":{"clear-env":false,"description":"A
            Cloud Native Buildpack that provides the Bellsoft Liberica implementations
            of JREs and JDKs","homepage":"https://github.com/paketo-buildpacks/bellsoft-liberica","id":"paketo-buildpacks/bellsoft-liberica","keywords":["java","jvm","jre","jdk"],"licenses":[{"type":"Apache-2.0","uri":"https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/LICENSE"}],"name":"Paketo
            BellSoft Liberica Buildpack","sbom-formats":["application/vnd.syft+json","application/vnd.cyclonedx+json"],"version":"9.0.1"},"build":false,"launch":true,"cache":false},"jre":{"sha":"sha256:318d4c9505d84ed07c3b75cb0edbd034e6deeac1e5cdf03712b3a648c221e1bc","data":{"cert-file":"b1cd670e1f6326d4613d81a1543fe3944e6f140f4f60b70f7390c5ff70cd8f22","dependency":{"cpes":["cpe:2.3:a:oracle:jre:11.0.13:*:*:*:*:*:*:*"],"id":"jre","licenses":[{"type":"GPL-2.0
            WITH Classpath-exception-2.0","uri":"https://openjdk.java.net/legal/gplv2+ce.html"}],"name":"BellSoft
            Liberica JRE","purl":"pkg:generic/bellsoft-jre@11.0.13?arch=amd64","sha256":"8bad208be75e67204bcc90cafc35d73506a0ec7cfc384674595003db69241965","stacks":["io.buildpacks.stacks.bionic","io.paketo.stacks.tiny","*"],"uri":"https://github.com/bell-sw/Liberica/releases/download/11.0.13+8/bellsoft-jre11.0.13+8-linux-amd64.tar.gz","version":"11.0.13"}},"build":false,"launch":true,"cache":false}}},{"key":"paketo-buildpacks/syft","version":"1.2.0","layers":{}},{"key":"paketo-buildpacks/maven","version":"6.0.1","layers":{}},{"key":"paketo-buildpacks/executable-jar","version":"6.0.1","layers":{"classpath":{"sha":"sha256:7fbc97c38fad01ae2b8189c8d9a0a0149932192accc4ad253b0f8186d0793e9a","data":{"classpath":["/workspace"],"launch":true},"build":true,"launch":true,"cache":false}}},{"key":"paketo-buildpacks/apache-tomcat","version":"7.0.2","layers":{}},{"key":"paketo-buildpacks/dist-zip","version":"5.0.1","layers":{}},{"key":"paketo-buildpacks/spring-boot","version":"5.2.0","layers":{"helper":{"sha":"sha256:a174aef9927e9ab94b0a99a2b93965993efda3aee99ff1399e67396a8637ebad","data":{"clear-env":false,"description":"A
            Cloud Native Buildpack that contributes Spring Boot dependency information
            and slices an application into multiple layers","homepage":"https://github.com/paketo-buildpacks/spring-boot","id":"paketo-buildpacks/spring-boot","keywords":["java","spring","spring-boot"],"licenses":[{"type":"Apache-2.0","uri":"https://github.com/paketo-buildpacks/spring-boot/blob/main/LICENSE"}],"name":"Paketo
            Spring Boot Buildpack","sbom-formats":["application/vnd.cyclonedx+json","application/vnd.syft+json"],"version":"5.2.0"},"build":false,"launch":true,"cache":false},"spring-cloud-bindings":{"sha":"sha256:6182ede4914f7f528e5044b2ee03e11dfc61661ebada00f0abd117bb58684eea","data":{"cpes":["cpe:2.3:a:vmware:spring_cloud_bindings:1.8.0:*:*:*:*:*:*:*"],"id":"spring-cloud-bindings","licenses":[{"type":"Apache-2.0","uri":"https://github.com/spring-cloud/spring-cloud-bindings/blob/main/LICENSE"}],"name":"Spring
            Cloud Bindings","purl":"pkg:generic/springframework/spring-cloud-bindings@1.8.0","sha256":"c75ef3152817c28c7049d7e0052dfba3ed461a7151984e594b656c0be927888e","stacks":["io.buildpacks.stacks.bionic","io.paketo.stacks.tiny","*"],"uri":"https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.8.0/spring-cloud-bindings-1.8.0.jar","version":"1.8.0"},"build":false,"launch":true,"cache":false},"web-application-type":{"sha":"sha256:6763b99e37924a36f5ebbaa60cceda209369919ee2ff6b0623381f10222a4dfd","data":{"files":"51be6f7e9b4d4d748c3954009e8ffc7c6093e8cff86d13e3d40353ccb690670b"},"build":false,"launch":true,"cache":false}}}],"config":{"sha":"sha256:7fa0c0a5d132847ad25ae9005a959faf7b69d002675217f03e2ab9d1dab14f9a"},"launcher":{"sha":"sha256:ab2b7fb6b8c06013debf1fc85d68a492215398fc58d076f86759eabeaa76d3d7"},"process-types":{"sha":"sha256:1dc94a70dbaa2171fb086500a5d27797f779219b126b0a1eebb9180c2792e80e"},"runImage":{"topLayer":"sha256:d7467baf869b85ae4a6df9a7f06f008bf1e41c4d5f4916c399e602a94d0b7cc4","reference":"0d382d05205978c348b29b35331bbbe0200b93a4b55f33934cf6131dbaa86337"},"stack":{"runImage":{"image":"index.docker.io/paketobuildpacks/run:tiny-cnb","mirrors":["gcr.io/paketo-buildpacks/run:tiny-cnb"]}}}'
          io.buildpacks.project.metadata: '{}'
          io.buildpacks.stack.description: distroless-like bionic + glibc + openssl
            + CA certs
          io.buildpacks.stack.distro.name: Ubuntu
          io.buildpacks.stack.distro.version: "18.04"
          io.buildpacks.stack.homepage: https://github.com/paketo-buildpacks/stacks
          io.buildpacks.stack.id: io.paketo.stacks.tiny
          io.buildpacks.stack.maintainer: Paketo Buildpacks
          io.buildpacks.stack.metadata: '{"base-image": "paketobuildpacks/run@sha256:b91c81d8292fb0bfa9b9a9e965cb76d08196ec921b541bf191210ee9714dc133"}'
          io.buildpacks.stack.mixins: '["base-files","ca-certificates","libc6","libssl1.1","netbase","openssl","tzdata","zlib1g"]'
          io.buildpacks.stack.released: "2021-12-08T02:03:45Z"
          io.paketo.stack.packages: '[{"name":"base-files","version":"10.1ubuntu2.11","arch":"amd64","source":{"name":"base-files","version":"10.1ubuntu2.11","upstreamVersion":"10.1ubuntu2.11"},"summary":"Debian
            base system miscellaneous files"},{"name":"ca-certificates","version":"20210119~18.04.2","arch":"all","source":{"name":"ca-certificates","version":"20210119~18.04.2","upstreamVersion":"20210119~18.04.2"},"summary":"Common
            CA certificates"},{"name":"libc6","version":"2.27-3ubuntu1.4","arch":"amd64","source":{"name":"glibc","version":"2.27-3ubuntu1.4","upstreamVersion":"2.27"},"summary":"GNU
            C Library: Shared libraries"},{"name":"libssl1.1","version":"1.1.1-1ubuntu2.1~18.04.14","arch":"amd64","source":{"name":"openssl","version":"1.1.1-1ubuntu2.1~18.04.14","upstreamVersion":"1.1.1"},"summary":"Secure
            Sockets Layer toolkit - shared libraries"},{"name":"netbase","version":"5.4","arch":"all","source":{"name":"netbase","version":"5.4","upstreamVersion":"5.4"},"summary":"Basic
            TCP/IP networking system"},{"name":"openssl","version":"1.1.1-1ubuntu2.1~18.04.14","arch":"amd64","source":{"name":"openssl","version":"1.1.1-1ubuntu2.1~18.04.14","upstreamVersion":"1.1.1"},"summary":"Secure
            Sockets Layer toolkit - cryptographic utility"},{"name":"tzdata","version":"2021e-0ubuntu0.18.04","arch":"all","source":{"name":"tzdata","version":"2021e-0ubuntu0.18.04","upstreamVersion":"2021e"},"summary":"time
            zone and daylight-saving time data"},{"name":"zlib1g","version":"1:1.2.11.dfsg-0ubuntu2","arch":"amd64","source":{"name":"zlib","version":"1:1.2.11.dfsg-0ubuntu2","upstreamVersion":"1.2.11.dfsg"},"summary":"compression
            library - runtime"}]'
          org.opencontainers.image.title: petclinic
          org.opencontainers.image.version: 2.5.0-SNAPSHOT
          org.springframework.boot.version: 2.5.6
        User: 1000:1000
        WorkingDir: /workspace
      created: "1980-01-01T00:00:01Z"
      history:
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      - created: "1980-01-01T00:00:01Z"
      os: linux
      rootfs:
        diff_ids:
        - sha256:5e2b7d52f6d04719743e8d25ddf1ef7f80168ed22a17b922b36560e08dce15e4
        - sha256:d7467baf869b85ae4a6df9a7f06f008bf1e41c4d5f4916c399e602a94d0b7cc4
        - sha256:56d5429304369d4c23b02aab20fd2667ef20ca47c579e02a361c249dedbfd5c2
        - sha256:1c3471643466fbf59df09102442337e03876bb1c8ee9b28140da48510ed87d4a
        - sha256:ec0381c8f32136ad9564b114b2271d1181e0c181957acb6707e6ff4713a7a89d
        - sha256:318d4c9505d84ed07c3b75cb0edbd034e6deeac1e5cdf03712b3a648c221e1bc
        - sha256:7fbc97c38fad01ae2b8189c8d9a0a0149932192accc4ad253b0f8186d0793e9a
        - sha256:a174aef9927e9ab94b0a99a2b93965993efda3aee99ff1399e67396a8637ebad
        - sha256:6182ede4914f7f528e5044b2ee03e11dfc61661ebada00f0abd117bb58684eea
        - sha256:6763b99e37924a36f5ebbaa60cceda209369919ee2ff6b0623381f10222a4dfd
        - sha256:4918492351c161334d213aa73bcfbe92fcb4f06ebfdc9e2de11916d111f10f52
        - sha256:a9e7448454f5fe4f6be1bc4a31004534d4dfeb1e743e11946d335b26ae8c17b2
        - sha256:c4537747ad1efb1f098a319cad22cb13212d9b2c325c48ef9154078d4eeb8868
        - sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
        - sha256:0f31e5b545554dfba40f6b369be06ac78c21190059d9166abbf46807aeac3cc0
        - sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
        - sha256:ab2b7fb6b8c06013debf1fc85d68a492215398fc58d076f86759eabeaa76d3d7
        - sha256:7fa0c0a5d132847ad25ae9005a959faf7b69d002675217f03e2ab9d1dab14f9a
        - sha256:1dc94a70dbaa2171fb086500a5d27797f779219b126b0a1eebb9180c2792e80e
        type: layers
    image: index.docker.io/scothis/petclinic@sha256:8b517f21f283229e855e316e2753396239884eb9c4009ab6c797bdf2a041140f
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: index.docker.io/scothis/petclinic@sha256:8b517f21f283229e855e316e2753396239884eb9c4009ab6c797bdf2a041140f
        name: workload
        resources: {}
status:
  appliedConventions: null
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers: null
